### ISSUE TITLE
Add Qubit.tv

### ISSUE THREAD

**Issue by 9acca9** [firsttris/chrome.sendtokodi#1]
Please can you add Qubit.tv??? 
Thanks

**Comment by firsttris** [comment]
Hey Sir,

the plugin uses youtube-dl (a multi site parser)
https://github.com/rg3/youtube-dl

Supported Sites:
https://rg3.github.io/youtube-dl/supportedsites.html

You have to make you feature request there... 

My plugin just provides the kodi support for youtube_dl, think about it like this.

regards
Tristan
