### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by gerion0** [firsttris/chrome.sendtokodi#2]
I would love to see this addon (or a similar one) in Firefox, too. In principal, both browsers support WebExtensions. However, this addon as is does not load in Firefox. Can this addon be updated in such a way that it is compatible with both browsers?

**Comment by firsttris** [comment]
i think this should be rather easily possible

https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

there is even a firefox page where you can test the extension and see whats wrong.

https://www.extensiontest.com/

**Comment by darodi** [comment]
@gerion0 
If you don't want to port the extension to firefox, there is another option.

I managed to convert the chrome extension to a firefox extension a few years ago using
https://github.com/Noitidart/Chrome-Store-Foxified/

However, Chrome-Store-Foxified doesn't work anymore with the last version of firefox.
There is a workaround on the project page that might still work though.
(convert the extension using an old version of firefox and copy the result .xpi file to your latest firefox).

I'm still using the converted extension from a few years ago  on the latest firefox and it's still working.

Good luck.

**Comment by firsttris** [comment]
has support now
