### ISSUE TITLE
The sendtokodi extension is no longer available in the chrome webstore

### ISSUE THREAD

**Issue by pitsi** [firsttris/chrome.sendtokodi#4]
Hello and thank you for your work on the main addon.

So, today I wanted to manually update an extension in brave, so I opened brave://extensions and I came accross this

![2022-05-01-090832_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/166134471-58ccd339-552b-4596-b73b-6e430df31d62.png)

I found out that the extension is not available anymore in the chrome webstore. A search for it returns no results and the link under "install" at the readme leads to a 404. If the extension was removed from the store, there is no need to mess with google's rules to add it back. 
Can you please add it as a crx file under the releases page? Just for us that do not know how to build with npm etc.

Thank you in advance :)

**Comment by AJolly** [comment]
Yep, not in webstore anymore.

**Comment by pitsi** [comment]
Did this make sendtokodi useless for you too? 
Because since this happened, the only thing that can actually utilize it is kore (the official remote control app for android), which supports sendtokodi since April 2021. Ok, I can send it anything to it and kodi will play it, but doing it from a desktop browser is far more convenient.

**Comment by firsttris** [comment]
You should also be able to install the extension manually.

If I find some time I will add it back to webstore

**Comment by pitsi** [comment]
Well, I have no problem installing it manualy... provided that I get it from a reliable source.
There are tons of sites that simply offer .crx files for download, but how credible can they be?
Having said that, I have to admit that I used such a site once to get it.

**Comment by firsttris** [comment]
I feel sorry mate, I will add such a file which you can just install.

**Comment by pitsi** [comment]
No need to apologise for google's decisions or even to try and re-add it to the store. 
Just add the crx file here so that everyone can get it without second thoughts :)

**Comment by TheColorman** [comment]
> I feel sorry mate, I will add such a file which you can just install.

Any update on this? ~~I get errors building the extension locally, so I would love to get access to the built extension.~~
I did manage to build it, just had to set `NODE_OPTIONS=--openssl-legacy-provider` as an environment variable.

**Comment by pitsi** [comment]
Does anyone know where I can find the crx file so as to reinstall it? My brave crashed and lost all its settings, plus the extensions and all their settings too :(

**Comment by firsttris** [comment]
i fixed the build job and added zip of the build to the release page.

you would need to unzip it into a folder.

go to chrome - manage extensions
check developer mode
load unpacked extension (upper left corner) 
choose the folder where you unpacked the extension.


if you have some ideas how to update the readme please let me know

**Comment by firsttris** [comment]
creating a CRX can also be done via chrome but you need a valid certificate for this, its the next button.

once i have my chrome develop account setup again, i will reupload it to the store.

but there are some other extension where i need to fix the build first.

**Comment by pitsi** [comment]
Thank you sooo much! No offence, but I have no idea how to create a crx file. Your instructions with npm/yarn, but I'd rather stay away from nodejs and leave someone more experienced do the job.

Also, I do not know at which version was on the store, but I assume the one on releases is newer, right?

---edit
And it is not a crx file but a zip one :/

---re-edit
Ready!

![2023-11-22-131150_1280x1024_scrot](https://github.com/firsttris/chrome.sendtokodi/assets/5880037/25168add-b2f1-4122-8eb0-57fae7f5bcb0)

**Comment by firsttris** [comment]
you can just use the zip file from release unpack it:

- go to chrome 
- manage extensions
- check developer mode
- load unpacked extension (upper left corner)
- choose the folder where you unpacked the extension.

**Comment by firsttris** [comment]
CRX is only possible with chrome webstore and a valid certificate, this would be the next step.

sorry for the missunderstanding.

**Comment by pitsi** [comment]
No worries. I did the procedure you described above (I have developer mode always enabled), but instead of "load unpacked extension", I chose to pack it to a crx file because I want to send it to a friend.

**Comment by pitsi** [comment]
I updated it to v0.0.17 a few minutes ago and I decided to test it. The problem is... I can't edit any field!

![2023-11-23-133846_1280x1024_scrot](https://github.com/firsttris/chrome.sendtokodi/assets/5880037/11f8dcd5-a20e-4970-a869-346763026e8c)

**Comment by firsttris** [comment]
thanks for reporting, something broke while refactoring it.

i will fix it. you can still use an earlier release from the release page.

**Comment by pitsi** [comment]
I can wait. Meanwhile, I would like to try the firefox version that you mentioned in the other issue that is closed now.

**Comment by firsttris** [comment]
probably it has the same issue, also i have not created a release for firefox yet. i will need to create 2 releases

**Comment by firsttris** [comment]
you can also install the project and build a release yourself.

**Comment by pitsi** [comment]
I just rolled back to 0.0.15 to make it work, because 0.0.16 has the same issue as above.

**Comment by firsttris** [comment]
check version 18. 

let me know what works and what doesn't

**Comment by pitsi** [comment]
If you exclude that "new connection with id 1234567890", which was annoying to remove completely and create one with the name I want, the only thing that does not seem work is blank password. It just does not do anything when pressing test.

![2023-11-25-184149_1280x1024_scrot](https://github.com/firsttris/chrome.sendtokodi/assets/5880037/2c3faf0e-91e6-4e5f-94ec-a503de64f76c)

**Comment by firsttris** [comment]
Ok. i fixed that in version 19

If you create a new Item, the name will now be New 1, New 2, New 3 because you need to distiguish them even if you have not set a name.

also i made the password field not required.

it always sends a request no matter if there is a password or not.

**Comment by pitsi** [comment]
Sorry for not replying earlier, I am having a tiresome weekend with very little sleep.
I just built v21 and it works. It just says "Object object" at the bottom when pressing test.

**Comment by firsttris** [comment]
i wanted to add better status reporting, if the connection works.

its probably returning an error. 

i implemented a logic to serialize it to a string if the errorMessage is an object in v22

**Comment by pitsi** [comment]
Function over form! Do not waste your time on trivial stuff if you are done with the addon's core functionality.

**Comment by firsttris** [comment]
its important that the experience is kinda polished and that user are not confused with wired issues.

before i release to webstore again.

**Comment by pitsi** [comment]
Same thing with 22. No need to rush it though, I also want to take some time off too and relax :)

**Comment by firsttris** [comment]
the method "test" we were sending to kodi did no exist.

we are now calling "ping", if you press ping it should say "pong". means the connection works.

let me know you find any other issue.

**Comment by pitsi** [comment]
Ping and pong work fine.As usual, i deleted the addon and added it fresh, plus I configure it it every time from scratch.

**Comment by firsttris** [comment]
the addon sync's to chrome storage and this should even sync your settings across browsers if your logged in with your google account.

but yes if you install and delete development version it will wipe your settings, thats expected.

**Comment by firsttris** [comment]
i reactivated my chrome developer account and the extension is now in pending for review. it should even get the old chrome webstore url back.

**Comment by pitsi** [comment]
It's back on the store! Thank you so much!
Feel free to close this, if there is nothing else to add.

**Comment by pitsi** [comment]
I did not open gihub for only a couple of days and the addon version almost reached my age :D 
Really nice to see so frequent updates. On my end though, I thought the store would update it, but it was still on v0.0.23.
So I removed it, went back to the store and installed it from there... and it is on v0.0.23 there.

**Comment by firsttris** [comment]
There are no changes in the addon I'm just working on Build Scripts to
Automatically release add-on as release on the GitHub page and  to all
three stores. Chrome, Edge,Mozilla.

pitsi ***@***.***> schrieb am So., 3. Dez. 2023, 06:07:

**Comment by firsttris** [comment]
trying to automate the addon create and release process. so if im going to find contributors for the project they can just work on it and release a new version without that i need to put effort in releasing a new version.

also i have more chrome addons, want to use the build scripts for all of them, im just developing the scripts with this extension. after changing the script i need to test it, often it fails first and i need to rerun it a few times to sort out all issues.
